name: Build and push

on:
  push:
    branches:
      - "main"
      - "legacy/*"
  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/alvarosdev/docker-neoforge-zulu

jobs:
  build:
    name: üèÉ‚Äç‚ôÇÔ∏è Build container
    runs-on: ubuntu-latest
    # Permissions required for execution and pushing to GHCR
    permissions:
      contents: read
      packages: write

    steps:
      - name: üíª Checkout code
        uses: actions/checkout@v4

      - name: üì¶ Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: üì¶ Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: üîê Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: üìñ Read NeoForge Version
        id: neoforge_version
        run: |
          # 1. Load defaults from file
          if [ -f VERSION.txt ]; then
            source VERSION.txt
          else
            echo "::error::VERSION.txt not found"
            exit 1
          fi

          # 2. Output variables
          echo "version=$NFVERSION" >> $GITHUB_OUTPUT

      - name: üè∑Ô∏è Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=${{ steps.neoforge_version.outputs.version }}

      - name: üì¶ Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            NFVERSION=${{ steps.neoforge_version.outputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
