name: Build and push

on:
  push:
    branches:
      - "main"
      - "legacy/*"
  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/alvarosdev/zulu-fabricmc

jobs:
  build:
    name: üèÉ‚Äç‚ôÇÔ∏è Build container
    runs-on: ubuntu-latest
    # Permissions required for execution and pushing to GHCR
    permissions:
      contents: read
      packages: write

    steps:
      - name: üíª Checkout code
        uses: actions/checkout@v4

      - name: üì¶ Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: üì¶ Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: üîê Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: üìñ Read Fabric Version
        id: fabric_version
        run: |
          # 1. Load defaults from file
          if [ -f fabric_version.txt ]; then
            source fabric_version.txt
          else
            echo "::error::fabric_version.txt not found"
            exit 1
          fi

          # 2. Override if legacy branch
          if [[ "${{ github.ref_name }}" == legacy/* ]]; then
             echo "Detected legacy branch: ${{ github.ref_name }}"
             MC_VERSION=${GITHUB_REF_NAME#legacy/}
             echo "Overriding MC_VERSION to $MC_VERSION"
          fi

          # 3. Output variables
          echo "loader=$LOADER" >> $GITHUB_OUTPUT
          echo "mc_version=$MC_VERSION" >> $GITHUB_OUTPUT

      - name: üè∑Ô∏è Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=${{ steps.fabric_version.outputs.mc_version }}
            type=raw,value=${{ steps.fabric_version.outputs.mc_version }}-${{ steps.fabric_version.outputs.loader }}

      - name: üì¶ Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            MCVERSION=${{ steps.fabric_version.outputs.mc_version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
